version: '3.8'
services:
  web-admin:
    build:
      context: .
      dockerfile: web/web-admin/Dockerfile
    expose:
      - "8080"
    container_name: web-admin
    restart: always

  web-app:
    build:
      context: .
      dockerfile: web/web-app/Dockerfile
    expose:
      - "8080"
    container_name: web-app
    restart: always

  rent-house-admin:
    build:
      context: ./rentHouseAdmin
    container_name: rent-house-admin
    restart: always

  rent-house-h5:
    build:
      context: ./rentHouseH5
    container_name: rent-house-h5
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-admin
      - web-app
      - rent-house-admin
      - rent-house-h5
    container_name: nginx-gateway
    restart: always